accounts/urls.py
from django.urls import path 
from . import views 
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_page,name ='login'),
    path('signup/',views.registration_page,name='register'),
    path('logout/',views.logout_page,name ='logout'),
    path('<slug:username>/profile',views.profile_page,name ='profile'),
    path('user-like',views.user_like),
    path('user-follow',views.user_follow),
    path('user-profile-image-change',views.user_profile_image_change),
    path('user-profile-boi-change',views.user_profile_boi_change),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace='post') ),
    path('accounts/', include('accounts.urls',namespace='accounts') ),
]

if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'post'


urlpatterns = [ 
    path('',views.home,name='home'),
    path('search/',views.search,name='search'),
    path('post/<slug:slug>/',views.post_details,name='post-details'),
    path('post/post-like',views.post_like_add),
    path('post-add',views.post_add)

]

accounts/models.py
from distutils.command.upload import upload
from email.policy import default
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User 
# Create your models here.
def namer (instance ,filename):
    name  = instance.user.username+"/"+filename
    return name 
class Profile(models.Model):
    bio = models.TextField(blank=True,null=True)
    image  = models.ImageField(upload_to=namer,default='../static/default/1.png',blank=True,null=True)
    user  = models.OneToOneField(User,on_delete=models.CASCADE,blank=True,null=True)
    followers = models.ManyToManyField(User,related_name='followers')
    following =models.ManyToManyField(User,related_name='following')
    likes = models.ManyToManyField(User,related_name='likes')
    def get_likes_count(self):
        return self.likes.count()
    def get_followers_count(self):
        return self.followers.count()
    def get_follwing_count(self):
        return self.following.count()

    def __str__(self):
        return self.user.username
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={"class":"form-input form-user"}))
    password = forms.CharField(widget=forms.widgets.PasswordInput(attrs={"class":"form-input form-pass"}))



class RegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.widgets.TextInput(attrs={"class":"form-input form-user"}))
    password1 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={"class":"form-input form-pass"}))
    password2 = forms.CharField(widget=forms.widgets.PasswordInput(attrs={"class":"form-input form-pass"}))


    class Meta :    
        model = User 
        fields=['username','password1','password2']

    


    

accounts/views.py
import json
from sqlite3 import connect
from django.forms import ValidationError
from django.shortcuts import render
from .forms import LoginForm,RegistrationForm
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import redirect,get_object_or_404
from django.urls import reverse
from django.contrib.auth.models import User
from post.models import Post
from post.forms import PostCreate
from django.http import JsonResponse
from .models import Profile
from django.contrib.auth.decorators import login_required
# Create your views here.
@login_required
def user_profile_boi_change(request):
    data = {}
    data['success']=False
    if request.method=="POST":
        boi_body = request.POST.get("bioBody")
        profile = Profile.objects.get(user=request.user)
        profile.bio=boi_body 
        profile.save()
        data['bio']=profile.bio
        data['success']=True
    return JsonResponse(data)
@login_required
def user_profile_image_change(request):
    data = {}
    data['success']=False
    if request.method=="POST":
        image = request.FILES.get("image")
        profile = Profile.objects.get(user=request.user)
        profile.image=image 
        profile.save()
        data['imageUrl']=profile.image.url
        data['success']=True
    return JsonResponse(data)
def user_follow(request):
    data = {}
    if request.method=="POST":

        user_id = request.POST.get("user_id")
        user = get_object_or_404(User,id=user_id)
        if request.user in user.profile.followers.all():
            request.user.profile.following.remove(user) 
            user.profile.followers.remove(request.user)
            data['msg']='success'
            data['operation']='removing'
            data["count"]=user.profile.get_followers_count();
        else:
            request.user.profile.following.add(user) 
            user.profile.followers.add(request.user)
            data['msg']='success'
            data['operation']='adding'
            data["count"]=user.profile.get_followers_count();
        data['method']=request.method

        return JsonResponse(data)   
def user_like(request):
    data = {}

    if request.method=="POST":
        user_id = request.POST.get("user_id")
        user = get_object_or_404(User,id=user_id)
        if request.user in user.profile.likes.all():
            user.profile.likes.remove(request.user)
            data['msg']='success'
            data['operation']='removing'
        else:
            user.profile.likes.add(request.user)
            data['msg']='success'
            data['operation']='adding'
        data["count"]=user.profile.get_likes_count();
    return JsonResponse(data)
def profile_page(request,username=None):
    if username:
        user = User.objects.get(username=username)

    else:
        user=request.user
    posts = Post.objects.filter(user=user)
    if  posts.count()==0:
        posts = None 
    if user == request.user :
        my_form = PostCreate( request.POST or None)
    else:
        my_form = None
    if request.method=='POST':
        if my_form.is_valid:
            post = my_form.save(commit=False)
            
            post.title = post.body[0:10]
            post.user = request.user
            post.save()

            
            return redirect(reverse("accounts:profile",args={username:request.user.username})) 
    liked = request.user in user.profile.likes.all()
    followed = request.user in user.profile.followers.all()
    print('-------------')
    print(liked)
    print(followed)
    print('-------------')
    context = {
        "user":user,
        'posts':posts,
        'form':my_form,
        'followed':followed,
        'liked':liked
    }
    return render(request,'accounts/profile.html',context)
def login_page(request):
    my_form = LoginForm(request.POST or None)

    if request.method=="POST":
        if my_form.is_valid():
            username = my_form.cleaned_data.get("username")
            password= my_form.cleaned_data.get("password")
            print(username,password)
            user = authenticate(username=username,password=password)
            if user is not None:
                    login(request,user=user)
                    return redirect(reverse("post:home"))
    context = {
        "form":my_form
    }
    return render(request,'accounts/login.html',context) 

def logout_page(request):
    if request.user.is_authenticated:
        logout(request)
        return redirect(reverse("accounts:login"))

def registration_page(request):
    if request.user.is_authenticated:
        return redirect(reverse("accounts:logout"))
    my_form = RegistrationForm(request.POST or None )
    if request.method=="POST":
        if my_form.is_valid():
            user  = my_form.save(commit=False)
            #do something 
            # 
            user.save()
            return redirect(reverse("accounts:login"))
    context = {
        'form':my_form
    }
    return render(request,'accounts/registration.html',context) 


    

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block links  %}
<link rel='stylesheet' href='{% static "css/login.css" %}' />

{% endblock links %}
{% block title %}
login page
{% endblock title %}
{% block content  %}
<div class='login--page'>
    <form method="post" class='login--form'>
        {% csrf_token %}


        <div class='form--field'>
            <label class='form--field--label'>
                {{form.username.label}}
            </label>
            {{form.username}}
        </div>
        <div class='form--field'>
            <label class='form--field--label'>
                {{form.password.label}}
            </label>
            {{form.password}}
        </div>

        {% if form.errors %}

        <div class="errors">

            <p>Your username and password didn't match. Please try again.</p>

        </div>
        {% endif %}
        <button class='login--button'>login</button>
        <a href="{% url 'accounts:register' %}" class='login--button extra--class '>signup</a>

    </form>
</div>
{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{request.user.uername}} profile
{% endblock title  %}
{% block links  %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
{% endblock links %}
{% block content %}

<div class="profile-page">
    <div class="profile-wrapper">
        <div class="profile-glass">
        </div>
        <div class="profile--info">
            <div  class="profile--user--image--wrapper">
            {%  if user.profile.image %}
            <img class="profile--user--image" id='profile--user--image' src="{{user.profile.image.url}}" />
            {% else %}
            <img class="profile--user--image" id='profile--user--image' src="{%  static 'default/1.png' %}" />
            {% endif %}
            {% if form %}
            <label for='chose--image' class="profile--user--image--change">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-card-image" viewBox="0 0 16 16">
                      <path d="M6.002 5.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0z"/>
                      <path d="M1.5 2A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13zm13 1a.5.5 0 0 1 .5.5v6l-3.775-1.947a.5.5 0 0 0-.577.093l-3.71 3.71-2.66-1.772a.5.5 0 0 0-.63.062L1.002 12v.54A.505.505 0 0 1 1 12.5v-9a.5.5 0 0 1 .5-.5h13z"/>
                    </svg>

            </label>
            <input type="file" name="chose--image" id='chose--image'/>
            {% endif %}
            </div>

            <h3 class="profile--user--username">{{user.username}}</h3>
            <div class="user--connections">
                <h5 class="profile--user--bio">following {{user.profile.get_follwing_count}}</h5>
                <h5 class="profile--user--bio" id="followers--count">followers {{user.profile.get_followers_count}}</h5>
                <h5 class="profile--user--bio" id ='likes--count'>people liked him {{user.profile.get_likes_count}}</h5>

      
            </div>
            <div class="bio--wrapper">
                <p class="profile--user--bio" id='profile--user--bio'>{{user.profile.bio}}</p>
                {% if form %}
                <textarea class="profile--user--bio--eddit" id='profile--user--bio--eddit'>
                    {{user.profile.bio}}
                </textarea>
                <button 
                id='bio--eddit--button' class="bio--eddit--button">
<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
  <path stroke-linecap="round" stroke-linejoin="round" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
</svg>
                </button>
                {% endif %}

            </div>
        </div>
        {% if form %}
        <form class="post-form" method="post" id="profile-post-form">
            {% csrf_token %}
            <div class="form--field">
                {{form.body}}
            </div>
            <button class="post-form-button" id="profile-post-form-button">post</button>
        </form>
        
        {% else %}
        <div class="follow--wrapper">

        {% if followed %}
        <button class="follow-btn cancel" id="follow-btn" user="{{user.id}}">unfollow</button>
        {% else %}
        <button class="follow-btn" id="follow-btn" user="{{user.id}}">follow</button>

        {%endif%}
        {% if liked %}
        <button class="follow-btn cancel" id="like-btn" user="{{user.id}}">dislike</button>

        {% else %}
        <button class="follow-btn" id="like-btn" user="{{user.id}}">like</button>

        {%endif%}

    </div>
        {% endif %}
       <div class="profile--posts" id="profile--posts">
        {% for post in posts %}

        <a class="profile--post "  href="{% url 'post:post-details' post.slug %} ">
                <p class="post--body--text">{{post.body}}</p>
                <div class="post--info">
                    <div class="post--info--childs profile--post--info--likes">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
                          </svg>
                          <span class="profile--post--info--likes--count">{{post.get_likes_count}}</span>

                    </div>
                    <div class="post--info--childs  profile--post--info--comments">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6"  viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
                          </svg>
                          <span class="profile--post--info--comments--count">{{post.get_comments_count}}</span>

                    </div>
                </div>
            </a>
        {% endfor%}
    </div>
    </div>

</div>
<script src="{% static 'js/profile.js' %}"></script>
{% endblock content %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}
{% load static %}
{% block links  %}
<link rel='stylesheet' href='{% static "css/login.css" %}' />

{% endblock links %}
{% block title %}
sign up page
{% endblock title %}
{% block content  %}
<div class='login--page'>
    <form method="post" class='login--form'>
        {% csrf_token %}


        <div class='form--field'>
            <label class="form--field--label">
            {{form.username.label}}
        </label>
            {{form.username}}
        </div>
        <div class='form--field'>
            <label class="form--field--label">
                password
            </label>
            {{form.password1}}
        </div>
        <div class='form--field'>
            <label class="form--field--label">
                    password confirmation
            </label>
            {{form.password2}}
        </div>
        {% if form.errors %}

        <div class="errors">

            <p>Your username is used before or your password is too weak ;-) </p>

        </div>
        {% endif %}
        <button class='login--button'>sign up</button>
        <a href="{% url 'accounts:login' %}" class='login--button extra--class '>login</a>

    </form>
</div>
{% endblock content %}