accounts/urls.py
from django.urls import path 
from . import views 
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login_page,name ='login'),
    path('signup/',views.registration_page,name='register'),
    path('logout/',views.logout_page,name ='logout'),
    path('<slug:username>/profile',views.profile_page,name ='profile'),
    path('user-like',views.user_like),
    path('user-follow',views.user_follow),
    path('user-profile-image-change',views.user_profile_image_change),
    path('user-profile-boi-change',views.user_profile_boi_change),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls',namespace='post') ),
    path('accounts/', include('accounts.urls',namespace='accounts') ),
]

if settings.DEBUG:
    urlpatterns  += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = 'post'


urlpatterns = [ 
    path('',views.home,name='home'),
    path('search/',views.search,name='search'),
    path('post/<slug:slug>/',views.post_details,name='post-details'),
    path('post/post-like',views.post_like_add),
    path('post-add',views.post_add)

]

templates/base.html
{% load static    %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock title %}</title>
    <link rel='stylesheet' href='{% static "css/main.css" %}'></link>
    {% block links %}
    
    {% endblock links %}
</head>

<body>


    <header class = 'main--header'>
        <nav class='header--nav'>
            <ul class='nav--menu'>
             <li ><a class ='menu--item' href='{% url "post:home" %}'> home</a></li>
             <li ><a class ='menu--item' href='{% url "post:search" %}'>search</a></li>
             <li ><a class ='menu--item'>news</a></li>
             <li ><a class ='menu--item'>about</a></li>
            </ul>
        </nav>
        {% if request.user.is_authenticated %}
        <div class='accounts'>
                <a href="{% url 'accounts:profile' request.user.username %}">
                <img class="accounts--user--image" src="{{request.user.profile.image.url}}" />
                <h4 class="accounts--user--username">{{request.user.username}}</h4>
            </a>
                <div class="user--actions">
                    <div class="user--action-section"><a class="logout--btn" href="{% url 'accounts:logout' %}">logout</a></div>
                </div>
        </div>
        {% else %}
        <div class="none-auth-user">
            <a class="none-auth-user--act" href="{% url 'accounts:register' %}"></a>
            <a class="none-auth-user--act login"  href="{% url 'accounts:login' %}"></a>
        </div>
        {% endif %}
    </header>


{% block content %}

{% endblock content %}  



</body>
</html>